-- Mock session data for demo recording
CREATE TABLE IF NOT EXISTS sessions (
    sid TEXT PRIMARY KEY,
    created TEXT,
    modified TEXT,
    mtime_epoch INTEGER,
    msg_count INTEGER,
    label TEXT,
    branch TEXT,
    project TEXT,
    cwd TEXT,
    search_text TEXT
);

INSERT INTO sessions VALUES ('a1b2c3d4-demo-0001', '2026-04-08', '2026-04-08', 1744100000, 47, 'add user authentication with OAuth2 and JWT tokens', 'feat/auth', 'web-platform', '/home/dev/web-platform', 'add user authentication with OAuth2 and JWT tokens implement login flow redirect callback token refresh middleware protect API endpoints session management cookie httponly secure google github provider passport strategy bcrypt password hashing rate limiting brute force protection CORS configuration environment variables secret rotation');

INSERT INTO sessions VALUES ('b2c3d4e5-demo-0002', '2026-04-07', '2026-04-08', 1744090000, 124, 'fix memory leak in websocket connection pool', 'fix/ws-leak', 'realtime-engine', '/home/dev/realtime-engine', 'fix memory leak in websocket connection pool investigate heap dump growing connections never released stale timeout idle cleanup graceful shutdown reconnect backoff exponential jitter prometheus metrics grafana dashboard alerting OOM killed pod kubernetes restart loop valgrind massif flamegraph allocation tracker drop impl RAII guard Arc reference cycle weak pointer');

INSERT INTO sessions VALUES ('c3d4e5f6-demo-0003', '2026-04-07', '2026-04-07', 1744080000, 89, 'migrate database from PostgreSQL to CockroachDB', 'feat/crdb-migration', 'data-service', '/home/dev/data-service', 'migrate database from PostgreSQL to CockroachDB schema compatibility serial vs UUID primary key distributed transactions read committed isolation level connection string DSN migration script flyway liquibase rollback strategy dual write shadow mode comparison testing latency percentiles p99 tail latency geographic partitioning multi-region follower reads');

INSERT INTO sessions VALUES ('d4e5f6g7-demo-0004', '2026-04-06', '2026-04-07', 1744070000, 203, 'build CLI tool for infrastructure deployment', 'main', 'deploy-cli', '/home/dev/deploy-cli', 'build CLI tool for infrastructure deployment terraform provider custom resource AWS CDK construct CloudFormation stack nested cross-account assume role MFA session token blue green canary deployment rolling update health check readiness probe load balancer target group auto scaling group launch template AMI packer golden image hardened CIS benchmark');

INSERT INTO sessions VALUES ('e5f6g7h8-demo-0005', '2026-04-06', '2026-04-06', 1744060000, 156, 'implement real-time collaborative editor with CRDT', 'feat/collab', 'notepad-app', '/home/dev/notepad-app', 'implement real-time collaborative editor with CRDT conflict-free replicated data type Yjs automerge operational transformation cursor presence awareness selection highlight undo redo history branching merge document tree rich text formatting bold italic heading list code block image embed drag drop resize collaborative cursors WebRTC signaling server STUN TURN relay peer connection data channel');

INSERT INTO sessions VALUES ('f6g7h8i9-demo-0006', '2026-04-05', '2026-04-06', 1744050000, 78, 'set up monitoring stack with Prometheus and Grafana', 'feat/observability', 'platform-infra', '/home/dev/platform-infra', 'set up monitoring stack with Prometheus and Grafana alertmanager PagerDuty integration Slack webhook notification routing silence inhibition recording rules aggregation histogram summary counter gauge service level objective SLO error budget burn rate alert multi-window strategy Loki log aggregation Tempo distributed tracing OpenTelemetry collector exporter');

INSERT INTO sessions VALUES ('g7h8i9j0-demo-0007', '2026-04-05', '2026-04-05', 1744040000, 312, 'karabasan — atmospheric horror game prototype', 'feat/world-gen', 'karabasan', '/home/dev/karabasan', 'karabasan atmospheric horror game prototype procedural world generation Perlin noise simplex octaves lacunarity persistence biome temperature humidity fog volumetric lighting shadow mapping deferred rendering PBR physically based material roughness metallic normal map ambient occlusion screen space reflection post processing bloom tone mapping exposure adaptation particle system ember dust mote wind simulation cloth physics ragdoll inverse kinematics animation state machine blend tree');

INSERT INTO sessions VALUES ('h8i9j0k1-demo-0008', '2026-04-04', '2026-04-05', 1744030000, 45, 'optimize Docker build with multi-stage and layer caching', 'chore/docker', 'api-gateway', '/home/dev/api-gateway', 'optimize Docker build with multi-stage and layer caching BuildKit cache mount secret mount SSH forward slim distroless scratch alpine musl static linking strip debug symbols UPX compression health check HEALTHCHECK CMD curl localhost readiness startup probe resource limits memory CPU request OOM score adjustment cgroup v2 rootless podman containerd');

INSERT INTO sessions VALUES ('i9j0k1l2-demo-0009', '2026-04-03', '2026-04-04', 1744020000, 67, 'refactor payment processing to event-driven architecture', 'feat/event-driven', 'billing-service', '/home/dev/billing-service', 'refactor payment processing to event-driven architecture Kafka topic partition consumer group offset commit exactly once semantics idempotency key dead letter queue retry exponential backoff circuit breaker saga pattern compensating transaction outbox pattern CDC change data capture Debezium connector Avro schema registry compatibility forward backward transactional');

INSERT INTO sessions VALUES ('j0k1l2m3-demo-0010', '2026-04-03', '2026-04-03', 1744010000, 91, 'implement end-to-end encryption for chat messages', 'feat/e2ee', 'messenger-app', '/home/dev/messenger-app', 'implement end-to-end encryption for chat messages Signal protocol double ratchet X3DH key agreement Curve25519 ECDH prekey bundle identity key signed prekey one-time prekey forward secrecy post-compromise security group messaging sender key tree KDF chain HKDF HMAC AES-256-GCM authenticated encryption nonce IV padding PKCS7 key rotation revocation certificate pinning');

INSERT INTO sessions VALUES ('k1l2m3n4-demo-0011', '2026-04-02', '2026-04-03', 1744000000, 34, 'debug flaky integration tests in CI pipeline', 'fix/flaky-tests', 'web-platform', '/home/dev/web-platform', 'debug flaky integration tests in CI pipeline race condition shared state test isolation database cleanup truncate transaction rollback parallel execution jest concurrent worker pool timeout retry mechanism seed randomization deterministic ordering beforeEach afterEach setup teardown mock clock fake timer dependency injection stub spy assertion eventually polling wait condition');

INSERT INTO sessions VALUES ('l2m3n4o5-demo-0012', '2026-04-01', '2026-04-02', 1743990000, 189, 'design and implement GraphQL federation gateway', 'feat/federation', 'api-gateway', '/home/dev/api-gateway', 'design and implement GraphQL federation gateway Apollo Router supergraph subgraph schema composition directive @key @shareable @external @requires entity reference resolver DataLoader batching N+1 query problem persisted queries automatic APQ complexity analysis depth limiting rate limiting field-level authorization directive custom scalar type union interface subscription WebSocket SSE');

INSERT INTO sessions VALUES ('m3n4o5p6-demo-0013', '2026-03-31', '2026-04-01', 1743980000, 56, 'set up Terraform modules for multi-account AWS landing zone', 'feat/landing-zone', 'terraform-infra', '/home/dev/terraform-infra', 'set up Terraform modules for multi-account AWS landing zone Control Tower organization OU service control policy SCP guardrail detective preventive account factory vending machine SSO permission set identity center SAML federation transit gateway VPC peering PrivateLink endpoint security group NACL flow logs CloudTrail GuardDuty SecurityHub Config compliance');

INSERT INTO sessions VALUES ('n4o5p6q7-demo-0014', '2026-03-30', '2026-03-31', 1743970000, 142, 'build machine learning pipeline for recommendation engine', 'feat/ml-pipeline', 'recommender', '/home/dev/recommender', 'build machine learning pipeline for recommendation engine collaborative filtering content-based hybrid approach matrix factorization SVD embedding vector similarity cosine dot product ANN approximate nearest neighbor FAISS index HNSW inverted file product quantization feature engineering categorical encoding one-hot target encoding feature store online serving batch prediction A/B testing experiment tracking MLflow model registry versioning');

INSERT INTO sessions VALUES ('o5p6q7r8-demo-0015', '2026-03-29', '2026-03-30', 1743960000, 28, 'write comprehensive API documentation with OpenAPI spec', 'docs/api', 'web-platform', '/home/dev/web-platform', 'write comprehensive API documentation with OpenAPI spec Swagger UI Redoc schema component request body response header parameter path query cookie authentication bearer token API key OAuth2 flow authorization code PKCE implicit client credentials example mock server Prism validation linting spectral ruleset changelog versioning deprecation sunset header');
